using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Gunluk.Migrations
{
    public partial class ilk : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Kategoriler",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Ad = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Kategoriler", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "Gonderiler",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Baslik = table.Column<string>(type: "nvarchar(400)", maxLength: 400, nullable: false),
                    Icerik = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Resim = table.Column<string>(type: "nvarchar(255)", maxLength: 255, nullable: true),
                    OlusturulmaZamani = table.Column<DateTime>(type: "datetime2", nullable: false),
                    DegistirilmeZamani = table.Column<DateTime>(type: "datetime2", nullable: false),
                    KategoriId = table.Column<int>(type: "int", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Gonderiler", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Gonderiler_Kategoriler_KategoriId",
                        column: x => x.KategoriId,
                        principalTable: "Kategoriler",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.InsertData(
                table: "Kategoriler",
                columns: new[] { "Id", "Ad" },
                values: new object[,]
                {
                    { 1, "Genel" },
                    { 2, "Gezilerim" },
                    { 3, "Mutfağım" },
                    { 4, "İş Dünyam" }
                });

            migrationBuilder.InsertData(
                table: "Gonderiler",
                columns: new[] { "Id", "Baslik", "DegistirilmeZamani", "Icerik", "KategoriId", "OlusturulmaZamani", "Resim" },
                values: new object[,]
                {
                    { 1, "Örnek Yazi 1", new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8671), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 1, new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8662), "" },
                    { 2, "Örnek Yazi 2", new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8700), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 1, new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8700), "" },
                    { 3, "Örnek Yazi 3", new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8702), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 1, new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8702), "" },
                    { 4, "Örnek Yazi 4", new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8703), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 1, new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8703), "" },
                    { 5, "Örnek Yazi 5", new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8705), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 1, new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8704), "" },
                    { 6, "Örnek Yazi 6", new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8706), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 1, new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8706), "" },
                    { 7, "Örnek Yazi 7", new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8708), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 1, new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8707), "" },
                    { 8, "Örnek Yazi 8", new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8709), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 1, new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8708), "" },
                    { 9, "Örnek Yazi 9", new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8710), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 1, new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8710), "" },
                    { 10, "Örnek Yazi 10", new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8711), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 1, new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8711), "" },
                    { 11, "Örnek Yazi 11", new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8713), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 1, new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8712), "" },
                    { 12, "Örnek Yazi 12", new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8714), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 1, new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8714), "" },
                    { 13, "Örnek Yazi 13", new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8715), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 2, new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8715), "" },
                    { 14, "Örnek Yazi 14", new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8716), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 2, new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8716), "" },
                    { 15, "Örnek Yazi 15", new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8718), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 2, new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8718), "" },
                    { 16, "Örnek Yazi 16", new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8719), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 2, new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8719), "" },
                    { 17, "Örnek Yazi 17", new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8720), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 2, new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8720), "" },
                    { 18, "Örnek Yazi 18", new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8722), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 2, new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8721), "" },
                    { 19, "Örnek Yazi 19", new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8723), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 2, new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8723), "" },
                    { 20, "Örnek Yazi 20", new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8724), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 2, new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8724), "" },
                    { 21, "Örnek Yazi 21", new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8726), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 2, new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8725), "" },
                    { 22, "Örnek Yazi 22", new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8727), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 2, new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8726), "" },
                    { 23, "Örnek Yazi 23", new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8728), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 2, new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8728), "" },
                    { 24, "Örnek Yazi 24", new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8729), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 2, new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8729), "" },
                    { 25, "Örnek Yazi 25", new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8730), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 3, new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8730), "" },
                    { 26, "Örnek Yazi 26", new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8732), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 3, new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8731), "" },
                    { 27, "Örnek Yazi 27", new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8733), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 3, new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8732), "" },
                    { 28, "Örnek Yazi 28", new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8734), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 3, new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8734), "" },
                    { 29, "Örnek Yazi 29", new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8735), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 3, new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8735), "" },
                    { 30, "Örnek Yazi 30", new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8736), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 3, new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8736), "" },
                    { 31, "Örnek Yazi 31", new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8738), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 3, new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8737), "" },
                    { 32, "Örnek Yazi 32", new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8739), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 3, new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8738), "" },
                    { 33, "Örnek Yazi 33", new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8740), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 3, new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8740), "" },
                    { 34, "Örnek Yazi 34", new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8741), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 3, new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8741), "" },
                    { 35, "Örnek Yazi 35", new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8742), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 3, new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8742), "" },
                    { 36, "Örnek Yazi 36", new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8743), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 3, new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8743), "" },
                    { 37, "Örnek Yazi 37", new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8745), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 4, new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8744), "" },
                    { 38, "Örnek Yazi 38", new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8746), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 4, new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8746), "" },
                    { 39, "Örnek Yazi 39", new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8747), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 4, new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8747), "" },
                    { 40, "Örnek Yazi 40", new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8749), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 4, new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8748), "" },
                    { 41, "Örnek Yazi 41", new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8750), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 4, new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8749), "" },
                    { 42, "Örnek Yazi 42", new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8751), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 4, new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8751), "" }
                });

            migrationBuilder.InsertData(
                table: "Gonderiler",
                columns: new[] { "Id", "Baslik", "DegistirilmeZamani", "Icerik", "KategoriId", "OlusturulmaZamani", "Resim" },
                values: new object[,]
                {
                    { 43, "Örnek Yazi 43", new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8752), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 4, new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8752), "" },
                    { 44, "Örnek Yazi 44", new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8753), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 4, new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8753), "" },
                    { 45, "Örnek Yazi 45", new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8755), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 4, new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8754), "" },
                    { 46, "Örnek Yazi 46", new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8756), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 4, new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8755), "" },
                    { 47, "Örnek Yazi 47", new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8757), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 4, new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8757), "" },
                    { 48, "Örnek Yazi 48", new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8758), "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>", 4, new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8758), "" }
                });

            migrationBuilder.CreateIndex(
                name: "IX_Gonderiler_KategoriId",
                table: "Gonderiler",
                column: "KategoriId");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Gonderiler");

            migrationBuilder.DropTable(
                name: "Kategoriler");
        }
    }
}
