// <auto-generated />
using System;
using Gunluk.DATA;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gunluk.Migrations
{
    [DbContext(typeof(UygulamaDbContext))]
    [Migration("20230110121954_ilk")]
    partial class ilk
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Gunluk.DATA.Gonderi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<DateTime>("DegistirilmeZamani")
                        .HasColumnType("datetime2");

                    b.Property<string>("Icerik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KategoriId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturulmaZamani")
                        .HasColumnType("datetime2");

                    b.Property<string>("Resim")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.ToTable("Gonderiler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Baslik = "Örnek Yazi 1",
                            DegistirilmeZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8671),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8662),
                            Resim = ""
                        },
                        new
                        {
                            Id = 2,
                            Baslik = "Örnek Yazi 2",
                            DegistirilmeZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8700),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8700),
                            Resim = ""
                        },
                        new
                        {
                            Id = 3,
                            Baslik = "Örnek Yazi 3",
                            DegistirilmeZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8702),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8702),
                            Resim = ""
                        },
                        new
                        {
                            Id = 4,
                            Baslik = "Örnek Yazi 4",
                            DegistirilmeZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8703),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8703),
                            Resim = ""
                        },
                        new
                        {
                            Id = 5,
                            Baslik = "Örnek Yazi 5",
                            DegistirilmeZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8705),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8704),
                            Resim = ""
                        },
                        new
                        {
                            Id = 6,
                            Baslik = "Örnek Yazi 6",
                            DegistirilmeZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8706),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8706),
                            Resim = ""
                        },
                        new
                        {
                            Id = 7,
                            Baslik = "Örnek Yazi 7",
                            DegistirilmeZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8708),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8707),
                            Resim = ""
                        },
                        new
                        {
                            Id = 8,
                            Baslik = "Örnek Yazi 8",
                            DegistirilmeZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8709),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8708),
                            Resim = ""
                        },
                        new
                        {
                            Id = 9,
                            Baslik = "Örnek Yazi 9",
                            DegistirilmeZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8710),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8710),
                            Resim = ""
                        },
                        new
                        {
                            Id = 10,
                            Baslik = "Örnek Yazi 10",
                            DegistirilmeZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8711),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8711),
                            Resim = ""
                        },
                        new
                        {
                            Id = 11,
                            Baslik = "Örnek Yazi 11",
                            DegistirilmeZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8713),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8712),
                            Resim = ""
                        },
                        new
                        {
                            Id = 12,
                            Baslik = "Örnek Yazi 12",
                            DegistirilmeZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8714),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8714),
                            Resim = ""
                        },
                        new
                        {
                            Id = 13,
                            Baslik = "Örnek Yazi 13",
                            DegistirilmeZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8715),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8715),
                            Resim = ""
                        },
                        new
                        {
                            Id = 14,
                            Baslik = "Örnek Yazi 14",
                            DegistirilmeZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8716),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8716),
                            Resim = ""
                        },
                        new
                        {
                            Id = 15,
                            Baslik = "Örnek Yazi 15",
                            DegistirilmeZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8718),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8718),
                            Resim = ""
                        },
                        new
                        {
                            Id = 16,
                            Baslik = "Örnek Yazi 16",
                            DegistirilmeZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8719),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8719),
                            Resim = ""
                        },
                        new
                        {
                            Id = 17,
                            Baslik = "Örnek Yazi 17",
                            DegistirilmeZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8720),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8720),
                            Resim = ""
                        },
                        new
                        {
                            Id = 18,
                            Baslik = "Örnek Yazi 18",
                            DegistirilmeZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8722),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8721),
                            Resim = ""
                        },
                        new
                        {
                            Id = 19,
                            Baslik = "Örnek Yazi 19",
                            DegistirilmeZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8723),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8723),
                            Resim = ""
                        },
                        new
                        {
                            Id = 20,
                            Baslik = "Örnek Yazi 20",
                            DegistirilmeZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8724),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8724),
                            Resim = ""
                        },
                        new
                        {
                            Id = 21,
                            Baslik = "Örnek Yazi 21",
                            DegistirilmeZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8726),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8725),
                            Resim = ""
                        },
                        new
                        {
                            Id = 22,
                            Baslik = "Örnek Yazi 22",
                            DegistirilmeZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8727),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8726),
                            Resim = ""
                        },
                        new
                        {
                            Id = 23,
                            Baslik = "Örnek Yazi 23",
                            DegistirilmeZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8728),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8728),
                            Resim = ""
                        },
                        new
                        {
                            Id = 24,
                            Baslik = "Örnek Yazi 24",
                            DegistirilmeZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8729),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8729),
                            Resim = ""
                        },
                        new
                        {
                            Id = 25,
                            Baslik = "Örnek Yazi 25",
                            DegistirilmeZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8730),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8730),
                            Resim = ""
                        },
                        new
                        {
                            Id = 26,
                            Baslik = "Örnek Yazi 26",
                            DegistirilmeZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8732),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8731),
                            Resim = ""
                        },
                        new
                        {
                            Id = 27,
                            Baslik = "Örnek Yazi 27",
                            DegistirilmeZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8733),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8732),
                            Resim = ""
                        },
                        new
                        {
                            Id = 28,
                            Baslik = "Örnek Yazi 28",
                            DegistirilmeZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8734),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8734),
                            Resim = ""
                        },
                        new
                        {
                            Id = 29,
                            Baslik = "Örnek Yazi 29",
                            DegistirilmeZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8735),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8735),
                            Resim = ""
                        },
                        new
                        {
                            Id = 30,
                            Baslik = "Örnek Yazi 30",
                            DegistirilmeZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8736),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8736),
                            Resim = ""
                        },
                        new
                        {
                            Id = 31,
                            Baslik = "Örnek Yazi 31",
                            DegistirilmeZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8738),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8737),
                            Resim = ""
                        },
                        new
                        {
                            Id = 32,
                            Baslik = "Örnek Yazi 32",
                            DegistirilmeZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8739),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8738),
                            Resim = ""
                        },
                        new
                        {
                            Id = 33,
                            Baslik = "Örnek Yazi 33",
                            DegistirilmeZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8740),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8740),
                            Resim = ""
                        },
                        new
                        {
                            Id = 34,
                            Baslik = "Örnek Yazi 34",
                            DegistirilmeZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8741),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8741),
                            Resim = ""
                        },
                        new
                        {
                            Id = 35,
                            Baslik = "Örnek Yazi 35",
                            DegistirilmeZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8742),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8742),
                            Resim = ""
                        },
                        new
                        {
                            Id = 36,
                            Baslik = "Örnek Yazi 36",
                            DegistirilmeZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8743),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8743),
                            Resim = ""
                        },
                        new
                        {
                            Id = 37,
                            Baslik = "Örnek Yazi 37",
                            DegistirilmeZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8745),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8744),
                            Resim = ""
                        },
                        new
                        {
                            Id = 38,
                            Baslik = "Örnek Yazi 38",
                            DegistirilmeZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8746),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8746),
                            Resim = ""
                        },
                        new
                        {
                            Id = 39,
                            Baslik = "Örnek Yazi 39",
                            DegistirilmeZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8747),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8747),
                            Resim = ""
                        },
                        new
                        {
                            Id = 40,
                            Baslik = "Örnek Yazi 40",
                            DegistirilmeZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8749),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8748),
                            Resim = ""
                        },
                        new
                        {
                            Id = 41,
                            Baslik = "Örnek Yazi 41",
                            DegistirilmeZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8750),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8749),
                            Resim = ""
                        },
                        new
                        {
                            Id = 42,
                            Baslik = "Örnek Yazi 42",
                            DegistirilmeZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8751),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8751),
                            Resim = ""
                        },
                        new
                        {
                            Id = 43,
                            Baslik = "Örnek Yazi 43",
                            DegistirilmeZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8752),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8752),
                            Resim = ""
                        },
                        new
                        {
                            Id = 44,
                            Baslik = "Örnek Yazi 44",
                            DegistirilmeZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8753),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8753),
                            Resim = ""
                        },
                        new
                        {
                            Id = 45,
                            Baslik = "Örnek Yazi 45",
                            DegistirilmeZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8755),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8754),
                            Resim = ""
                        },
                        new
                        {
                            Id = 46,
                            Baslik = "Örnek Yazi 46",
                            DegistirilmeZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8756),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8755),
                            Resim = ""
                        },
                        new
                        {
                            Id = 47,
                            Baslik = "Örnek Yazi 47",
                            DegistirilmeZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8757),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8757),
                            Resim = ""
                        },
                        new
                        {
                            Id = 48,
                            Baslik = "Örnek Yazi 48",
                            DegistirilmeZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8758),
                            Icerik = "\r\n                     <p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.</p>\r\n                     <p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 10, 15, 19, 54, 668, DateTimeKind.Local).AddTicks(8758),
                            Resim = ""
                        });
                });

            modelBuilder.Entity("Gunluk.DATA.Kategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Kategoriler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Genel"
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Gezilerim"
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Mutfağım"
                        },
                        new
                        {
                            Id = 4,
                            Ad = "İş Dünyam"
                        });
                });

            modelBuilder.Entity("Gunluk.DATA.Gonderi", b =>
                {
                    b.HasOne("Gunluk.DATA.Kategori", "Kategori")
                        .WithMany("Gonderiler")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("Gunluk.DATA.Kategori", b =>
                {
                    b.Navigation("Gonderiler");
                });
#pragma warning restore 612, 618
        }
    }
}
